apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drone-changeset
    component: drone
    env: prod
  name: drone-changeset
  namespace: drone
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: drone-changeset
      component: drone
      env: prod
  template:
    metadata:
      labels:
        app: drone-changeset
        component: drone
        env: prod
    spec:
      containers:
      - args: []
        command: []
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: changeset_github_key
              name: drone
        - name: PLUGIN_SECRET
          valueFrom:
            secretKeyRef:
              key: drone_rpc_secret
              name: drone
        image: microadam/drone-config-changeset-conditional:latest
        name: drone-changeset
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts: []
      initContainers: []
      serviceAccountName: default
