apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: external-dns
    component: external-dns
    env: prod
  name: external-dns
  namespace: utility
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: external-dns
      component: external-dns
      env: prod
  template:
    metadata:
      labels:
        app: external-dns
        component: external-dns
        env: prod
    spec:
      containers:
      - args:
        - --source=service
        - --source=ingress
        - --domain-filter=nhyne.dev
        - --domain-filter=nhyne.io
        - --domain-filter=adamjohnson.dev
        - --domain-filter=johnsona.dev
        - --provider=google
        - --registry=txt
        - '--txt-owner-id=nhyne-kube-utility '
        command: []
        env: []
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.11
        name: external-dns
        ports: []
        volumeMounts: []
      initContainers: []
      serviceAccountName: external-dns
  volumeClaimTemplates: []
