apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: archiver
commonLabels:
  env: minikube
bases:
  - ../../base
resources:
  - postgres.yml
  - diesel-init.yml
patches:
  - rust-api.yml
